### PR TITLE
Fix datetime comparison when there is no tzinfo and autotype sequence none check

### PR DESCRIPTION
**Pull request by whwright**
Resolves issues: https://github.com/pschmitt/pykeepass/issues/115 and https://github.com/pschmitt/pykeepass/issues/117

### CODE REVIEW

**Comment by Evidlo** [comment]
I think pschmitt likes to do the version bumping himself.

Could we get tests added for these two issues?

Also, you might be interested in [passhole](https://github.com/Evidlo/passhole), since you seem to be working on a Keepass CLI tool.

**Comment by whwright** [comment]
Test! FWIW I did some TDD by reverted my changes, wrote tests, made sure they blew up, and added my changes back.

Also `passhole` looks awesome, but the focus of my tool is very narrow for something I do in a personal workflow.

**Comment by Evidlo** [comment]
Could you use `kp.add_entry` instead of instantiating those entries yourself?

Also, you can use `git commit --amend --no-edit` and `git push -f` to make changes without adding new commits to your PR.

**Comment by Evidlo** [comment]
That's because I wrote `EntryTests` to be independent from `add_entry` failures.  All other tests that create entries use `add_entry`.  Using `Entry` directly is discouraged because it tends to change often.

**Comment by whwright** [comment]
I think it makes sense to instantiate the `Entry` object directly to isolate this unit test as much as possible. `add_entry` should be tested separately, which it is. You will have to update the `EntryTests` if the fundamentals of the objects change anyway.

The `add_entry` function also doesn't pass through an `element` property, which I am using in my test. Again it makes sense to me to do the testing at this level, and avoid any further re-factoring or munging with the private instance properties.

What is your opinion @pschmitt?

**Comment by whwright** [comment]
I have opened up a discrete issue for the auto type error, instead of having it piggyback here.

**Comment by Evidlo** [comment]
Looks good to me.

**Comment by whwright** [comment]
Awesome thank you! When do you typically do releases?

**Pull request merged**
