### PR TITLE
Fix use of libkeepass context manager

### PR DESCRIPTION
**Pull request by wget**
cf. [issue 44](https://github.com/pschmitt/pykeepass/issues/44)

### CODE REVIEW

**Comment by pschmitt** [comment]
So you suggest adding comments to the code? Am I missing something?

**Comment by wget** [comment]
@pschmitt For the time being yes. My initial patch (not visible any more in this PR) was to call the underlying libkeepass context manager (with `__exit__()`) and close the file descriptor from there. Indeed like explained, depending on the Python implementation, the garbage collector might not work like expected.
But for now, let's wait for the other libkeepass changes I have to be merged before merging this PR. :) I have further work to make on this PR.

**Comment by Evidlo** [comment]
The `libkeepass` changes have been merged.  When are we moving forward on this?

**Comment by wget** [comment]
@Evidlo Thanks for the reminder. Merging my csv based files to keypass is still on my todo, so this will be a task I will take up again in the days to come. I'm desperately waiting to get my end years holidays, where I'll be able to finally achieve this kind of personal work. Thanks for your patience any way!

**Comment by pschmitt** [comment]
Closing this since libkeepass is not longer relevant. See #87

**Pull request closed without merging**
