### PR TITLE
Fix use of keyfiles

### PR DESCRIPTION
**Pull request by eduarias**

### CODE REVIEW

**Comment by eduarias** [comment]
Sorry for dirty stuff around the pull request, now is cleaner in one one commit and no IDE files.

**Comment by pschmitt** [comment]
We are almost there, could you remove the changes to `setup.py` ? I'd like to take of version changes myself.

**Comment by eduarias** [comment]
Ok, `setup.py`removed from the PR

**Comment by pschmitt** [comment]
Nice work, thanks.

**Pull request merged**
